# Generated by Django 4.2.10 on 2024-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
