# Generated by Django 5.0.2 on 2024-03-03 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
    ]
