# Generated by Django 5.0.3 on 2024-03-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_email_alter_customuser_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('P', 'patient'), ('S', 'support'), ('A', 'assistent')], default='P', max_length=1),
        ),
    ]
