# Generated by Django 5.0.2 on 2024-03-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_email_alter_task_alarm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
    ]
