# Generated by Django 5.0.2 on 2024-03-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
