# Generated by Django 5.0.2 on 2024-03-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('P', 'patient'), ('S', 'support'), ('A', 'assistent')], default='P', max_length=1),
        ),
    ]
