# Generated by Django 5.0.2 on 2024-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
