# Generated by Django 5.0.2 on 2024-03-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='core.task'),
        ),
    ]
