# Generated by Django 5.0.2 on 2024-03-19 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customuser_associated_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='associated_user_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='associated_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='associated_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
