# Generated by Django 5.0.2 on 2024-03-21 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_customuser_associated_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_user',
            field=models.ManyToManyField(blank=True, related_name='associated_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
