# Generated by Django 5.0.3 on 2024-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customuser_associated_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
