# Generated by Django 5.0.2 on 2024-04-09 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_user',
            field=models.ManyToManyField(blank=True, related_name='associated_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
